export const SEARCH_RECIPES_START = 'SEARCH_RECIPES_START';
export const SEARCH_RECIPES_SUCCESS = 'SEARCH_RECIPES_SUCCESS';
export const FETCH_RECIPE_START = 'FETCH_RECIPE_START';
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const TOGGLE_ADD_NEW_INGREDIENT = 'TOGGLE_ADD_NEW_INGREDIENT';
export const SET_EDITED_INGREDIENT = 'SET_EDITED_INGREDIENT';